### PR TITLE
Added support for linking to lzma, bz2, dl, and rt via feature support.

### PR DESCRIPTION
**Pull request by ereichert**
@ryandbair I added dl and rt although I haven't needed them in tlx 2 yet.  I needed them in the c++ version and decided to knock them out in the hopes of not having to do this yak shaving again soon.

### CODE REVIEW

**Comment by ereichert** [comment]
@ryandbair There's a bug in this I didn't notice in the build output.

**Comment by ereichert** [comment]
@ryandbair I fixed the bug.  This PR is ready to go.

**Comment by ryandbair** [comment]
It looks good here. Please squash so we can merge with upstream.

**Comment by ereichert** [comment]
Will do the squash.  

We can't merge with upstream because of the version conflict.  I'm going to wait until they do a release and 2.8.7 is out before submitting the pull request.

Plus I want to make sure we have a majority of changes we need so we don't submit a lot of PR.

**Comment by ereichert** [comment]
@ryandbair Squashed.

**Pull request merged**
